# For local development
version: "2.2"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_app
    links:
      - redis
    ports:
      - "5000:5000"
      
  redis:
    image: redis
